"""config — re-exports all settings for backward-compatible `import config` usage."""
from .settings import *  # noqa: F401, F403
from .settings import (
    GEMINI_API_KEY, GEMINI_MODEL,
    GOOGLE_SERVICE_ACCOUNT_JSON,
    RAW_FOLDER_ID, PROCESSED_FOLDER_ID, REVIEW_FOLDER_ID,
    APPROVED_FOLDER_ID, PREVIEW_FOLDER_ID, PENDING_PAYMENT_FOLDER_ID, CLIPS_FOLDER_ID,
    OWNER_EMAIL, NOTIFY_EMAIL,
    LOGO_PATH, MUSIC_DIR, TMP_DIR, PROCESSED_IDS_FILE, LOG_FILE, CLIENTS_FILE,
    MAX_CUT_WORKERS, CLIPS_CACHE_DIR, FEEDBACK_FILE, REEL_METADATA_FILE,
    QA_CROP_CHECK, PENDING_UPLOADS_DIR, QUALITY_LOG_FILE,
    LANGSMITH_TRACING, LANGSMITH_PROJECT,
)
