-- Durable R2 source-upload manifest and exact-content duplicate resolution.
-- This is a focused GAP-015 foundation: it records every new R2 upload,
-- preserves first verification time, resolves byte-identical sources by SHA-256,
-- and leaves an immutable decision audit. Real R2/Android closure evidence remains required.

create table if not exists public.source_uploads (
  id                    uuid primary key default gen_random_uuid(),
  batch_id              text not null,
  storage_key           text not null unique,
  source_filename       text not null,
  mime_type             text,
  status                text not null default 'uploading'
                        check (status in ('uploading', 'verified', 'size_mismatch', 'superseded', 'failed')),
  source_size_bytes     bigint check (source_size_bytes is null or source_size_bytes >= 0),
  verified_size_bytes   bigint check (verified_size_bytes is null or verified_size_bytes >= 0),
  verified_at           timestamptz,
  content_sha256        text check (content_sha256 is null or content_sha256 ~ '^[0-9a-f]{64}$'),
  canonical_upload_id   uuid references public.source_uploads(id) on delete set null,
  superseded_at         timestamptz,
  supersede_reason      text,
  removed_at            timestamptz,
  removal_error         text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists source_uploads_batch_status_idx
  on public.source_uploads (batch_id, status, created_at);

create index if not exists source_uploads_sha_verified_idx
  on public.source_uploads (content_sha256, verified_at desc)
  where content_sha256 is not null and verified_at is not null;

alter table public.source_uploads enable row level security;
revoke all on table public.source_uploads from anon, authenticated;
grant select, insert, update, delete on table public.source_uploads to service_role;

create table if not exists public.source_upload_dedup_audit (
  id                       bigint generated by default as identity primary key,
  content_sha256           text not null check (content_sha256 ~ '^[0-9a-f]{64}$'),
  superseded_upload_id     uuid not null references public.source_uploads(id) on delete restrict,
  canonical_upload_id      uuid not null references public.source_uploads(id) on delete restrict,
  old_storage_key          text not null,
  new_storage_key          text not null,
  old_verified_at          timestamptz not null,
  new_verified_at          timestamptz not null,
  reason                   text not null default 'exact_content_duplicate'
                           check (reason = 'exact_content_duplicate'),
  decision_at              timestamptz not null default now(),
  removed_at               timestamptz,
  removal_error            text,
  unique (superseded_upload_id, canonical_upload_id, reason)
);

create index if not exists source_upload_dedup_audit_hash_idx
  on public.source_upload_dedup_audit (content_sha256, decision_at desc);

alter table public.source_upload_dedup_audit enable row level security;
revoke all on table public.source_upload_dedup_audit from anon, authenticated;
grant select, insert, update on table public.source_upload_dedup_audit to service_role;
grant usage, select on sequence public.source_upload_dedup_audit_id_seq to service_role;

create or replace function public.verify_source_upload(
  p_storage_key text,
  p_verified_size_bytes bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_upload public.source_uploads%rowtype;
begin
  if p_verified_size_bytes is null or p_verified_size_bytes < 0 then
    raise exception 'verified size must be a non-negative integer';
  end if;

  select *
    into v_upload
    from public.source_uploads
   where storage_key = p_storage_key
   for update;

  if not found then
    raise exception 'source upload for storage key % not found', p_storage_key;
  end if;

  if v_upload.status = 'superseded' then
    raise exception 'source upload % is superseded by %', v_upload.id, v_upload.canonical_upload_id;
  end if;

  if v_upload.source_size_bytes is not null
     and v_upload.source_size_bytes <> p_verified_size_bytes then
    update public.source_uploads
       set status = 'size_mismatch',
           verified_size_bytes = p_verified_size_bytes,
           updated_at = now()
     where id = v_upload.id
     returning * into v_upload;

    return jsonb_build_object(
      'upload_id', v_upload.id,
      'status', v_upload.status,
      'source_size_bytes', v_upload.source_size_bytes,
      'verified_size_bytes', v_upload.verified_size_bytes,
      'verified_at', v_upload.verified_at
    );
  end if;

  update public.source_uploads
     set status = 'verified',
         verified_size_bytes = p_verified_size_bytes,
         verified_at = coalesce(verified_at, now()),
         updated_at = now()
   where id = v_upload.id
   returning * into v_upload;

  return jsonb_build_object(
    'upload_id', v_upload.id,
    'status', v_upload.status,
    'source_size_bytes', v_upload.source_size_bytes,
    'verified_size_bytes', v_upload.verified_size_bytes,
    'verified_at', v_upload.verified_at
  );
end;
$$;

revoke all on function public.verify_source_upload(text, bigint) from public;
revoke all on function public.verify_source_upload(text, bigint) from anon;
revoke all on function public.verify_source_upload(text, bigint) from authenticated;
grant execute on function public.verify_source_upload(text, bigint) to service_role;

create or replace function public.resolve_exact_source_duplicate(
  p_upload_id uuid,
  p_content_sha256 text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hash text := lower(trim(coalesce(p_content_sha256, '')));
  v_current public.source_uploads%rowtype;
  v_canonical public.source_uploads%rowtype;
  v_superseded jsonb := '[]'::jsonb;
begin
  if v_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'content_sha256 must be 64 lowercase hexadecimal characters';
  end if;

  -- Different upload rows can discover the same hash concurrently. A transaction
  -- advisory lock derived from the hash serializes all canonical decisions for
  -- that exact content before any caller chooses or supersedes a source.
  perform pg_advisory_xact_lock(hashtextextended(v_hash, 0));

  select *
    into v_current
    from public.source_uploads
   where id = p_upload_id
   for update;

  if not found then
    raise exception 'source upload % not found', p_upload_id;
  end if;

  if v_current.verified_at is null or v_current.status not in ('verified', 'superseded') then
    raise exception 'source upload % is not verified', p_upload_id;
  end if;

  update public.source_uploads
     set content_sha256 = v_hash,
         updated_at = now()
   where id = p_upload_id;

  -- Lock all already-known rows with this byte hash before changing eligibility.
  perform 1
    from public.source_uploads
   where content_sha256 = v_hash
     and verified_at is not null
     and status in ('verified', 'superseded')
   order by verified_at desc, created_at desc, id desc
   for update;

  select *
    into v_canonical
    from public.source_uploads
   where content_sha256 = v_hash
     and verified_at is not null
     and status in ('verified', 'superseded')
   order by verified_at desc, created_at desc, id desc
   limit 1;

  if not found then
    raise exception 'no verified source upload found for hash %', v_hash;
  end if;

  insert into public.source_upload_dedup_audit (
    content_sha256,
    superseded_upload_id,
    canonical_upload_id,
    old_storage_key,
    new_storage_key,
    old_verified_at,
    new_verified_at,
    reason
  )
  select
    v_hash,
    candidate.id,
    v_canonical.id,
    candidate.storage_key,
    v_canonical.storage_key,
    candidate.verified_at,
    v_canonical.verified_at,
    'exact_content_duplicate'
  from public.source_uploads candidate
  where candidate.content_sha256 = v_hash
    and candidate.verified_at is not null
    and candidate.status in ('verified', 'superseded')
    and candidate.id <> v_canonical.id
  on conflict (superseded_upload_id, canonical_upload_id, reason) do nothing;

  update public.source_uploads
     set status = 'superseded',
         canonical_upload_id = v_canonical.id,
         superseded_at = coalesce(superseded_at, now()),
         supersede_reason = 'exact_content_duplicate',
         removal_error = null,
         updated_at = now()
   where content_sha256 = v_hash
     and verified_at is not null
     and status in ('verified', 'superseded')
     and id <> v_canonical.id;

  update public.source_uploads
     set status = 'verified',
         canonical_upload_id = v_canonical.id,
         superseded_at = null,
         supersede_reason = null,
         removal_error = null,
         updated_at = now()
   where id = v_canonical.id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'upload_id', candidate.id,
        'storage_key', candidate.storage_key,
        'verified_at', candidate.verified_at
      )
      order by candidate.verified_at asc, candidate.created_at asc, candidate.id asc
    ),
    '[]'::jsonb
  )
    into v_superseded
    from public.source_uploads candidate
   where candidate.content_sha256 = v_hash
     and candidate.id <> v_canonical.id
     and candidate.status = 'superseded'
     and candidate.removed_at is null;

  return jsonb_build_object(
    'content_sha256', v_hash,
    'canonical', jsonb_build_object(
      'upload_id', v_canonical.id,
      'storage_key', v_canonical.storage_key,
      'verified_at', v_canonical.verified_at
    ),
    'superseded', v_superseded
  );
end;
$$;

revoke all on function public.resolve_exact_source_duplicate(uuid, text) from public;
revoke all on function public.resolve_exact_source_duplicate(uuid, text) from anon;
revoke all on function public.resolve_exact_source_duplicate(uuid, text) from authenticated;
grant execute on function public.resolve_exact_source_duplicate(uuid, text) to service_role;
