-- Durable R2 source-upload manifest and exact-content duplicate resolution.
-- This is a focused GAP-015 foundation: it records every new R2 upload,
-- preserves first verification time, resolves byte-identical sources by SHA-256,
-- and leaves an immutable decision audit. Real R2/Android closure evidence remains required.

create table if not exists public.source_uploads (
  id                    uuid primary key default gen_random_uuid(),
  batch_id              text not null,
  storage_key           text not null unique,
  source_filename       text not null,
  mime_type             text,
  status                text not null default 'uploading'
                        check (status in ('uploading', 'verified', 'size_mismatch', 'superseded', 'failed')),
  source_size_bytes     bigint check (source_size_bytes is null or source_size_bytes >= 0),
  verified_size_bytes   bigint check (verified_size_bytes is null or verified_size_bytes >= 0),
  verified_at           timestamptz,
  content_sha256        text check (content_sha256 is null or content_sha256 ~ '^[0-9a-f]{64}$'),
  canonical_upload_id   uuid references public.source_uploads(id) on delete set null,
  superseded_at         timestamptz,
  supersede_reason      text,
  removed_at            timestamptz,
  removal_error         text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists source_uploads_batch_status_idx
  on public.source_uploads (batch_id, status, created_at);

create index if not exists source_uploads_sha_verified_idx
  on public.source_uploads (content_sha256, verified_at desc)
  where content_sha256 is not null and verified_at is not null;

alter table public.source_uploads enable row level security;
-- Service-role only. No anon/authenticated policies are intentionally created.

create table if not exists public.source_upload_dedup_audit (
  id                       bigint generated by default as identity primary key,
  content_sha256           text not null check (content_sha256 ~ '^[0-9a-f]{64}$'),
  superseded_upload_id     uuid not null references public.source_uploads(id) on delete restrict,
  canonical_upload_id      uuid not null references public.source_uploads(id) on delete restrict,
  old_storage_key          text not null,
  new_storage_key          text not null,
  old_verified_at          timestamptz not null,
  new_verified_at          timestamptz not null,
  reason                   text not null default 'exact_content_duplicate'
                           check (reason = 'exact_content_duplicate'),
  decision_at              timestamptz not null default now(),
  removed_at               timestamptz,
  removal_error            text,
  unique (superseded_upload_id, canonical_upload_id, reason)
);

create index if not exists source_upload_dedup_audit_hash_idx
  on public.source_upload_dedup_audit (content_sha256, decision_at desc);

alter table public.source_upload_dedup_audit enable row level security;
-- Service-role only. No anon/authenticated policies are intentionally created.

create or replace function public.resolve_exact_source_duplicate(
  p_upload_id uuid,
  p_content_sha256 text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hash text := lower(trim(coalesce(p_content_sha256, '')));
  v_current public.source_uploads%rowtype;
  v_canonical public.source_uploads%rowtype;
  v_superseded jsonb := '[]'::jsonb;
begin
  if v_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'content_sha256 must be 64 lowercase hexadecimal characters';
  end if;

  select *
    into v_current
    from public.source_uploads
   where id = p_upload_id
   for update;

  if not found then
    raise exception 'source upload % not found', p_upload_id;
  end if;

  if v_current.verified_at is null or v_current.status not in ('verified', 'superseded') then
    raise exception 'source upload % is not verified', p_upload_id;
  end if;

  update public.source_uploads
     set content_sha256 = v_hash,
         updated_at = now()
   where id = p_upload_id;

  -- Serialize decisions for every verified row with this exact byte hash.
  perform 1
    from public.source_uploads
   where content_sha256 = v_hash
     and verified_at is not null
     and status in ('verified', 'superseded')
   order by verified_at desc, created_at desc, id desc
   for update;

  select *
    into v_canonical
    from public.source_uploads
   where content_sha256 = v_hash
     and verified_at is not null
     and status in ('verified', 'superseded')
   order by verified_at desc, created_at desc, id desc
   limit 1;

  if not found then
    raise exception 'no verified source upload found for hash %', v_hash;
  end if;

  insert into public.source_upload_dedup_audit (
    content_sha256,
    superseded_upload_id,
    canonical_upload_id,
    old_storage_key,
    new_storage_key,
    old_verified_at,
    new_verified_at,
    reason
  )
  select
    v_hash,
    candidate.id,
    v_canonical.id,
    candidate.storage_key,
    v_canonical.storage_key,
    candidate.verified_at,
    v_canonical.verified_at,
    'exact_content_duplicate'
  from public.source_uploads candidate
  where candidate.content_sha256 = v_hash
    and candidate.verified_at is not null
    and candidate.status in ('verified', 'superseded')
    and candidate.id <> v_canonical.id
  on conflict (superseded_upload_id, canonical_upload_id, reason) do nothing;

  update public.source_uploads
     set status = 'superseded',
         canonical_upload_id = v_canonical.id,
         superseded_at = coalesce(superseded_at, now()),
         supersede_reason = 'exact_content_duplicate',
         removal_error = null,
         updated_at = now()
   where content_sha256 = v_hash
     and verified_at is not null
     and status in ('verified', 'superseded')
     and id <> v_canonical.id;

  update public.source_uploads
     set status = 'verified',
         canonical_upload_id = v_canonical.id,
         superseded_at = null,
         supersede_reason = null,
         removal_error = null,
         updated_at = now()
   where id = v_canonical.id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'upload_id', candidate.id,
        'storage_key', candidate.storage_key,
        'verified_at', candidate.verified_at
      )
      order by candidate.verified_at asc, candidate.created_at asc, candidate.id asc
    ),
    '[]'::jsonb
  )
    into v_superseded
    from public.source_uploads candidate
   where candidate.content_sha256 = v_hash
     and candidate.id <> v_canonical.id
     and candidate.status = 'superseded'
     and candidate.removed_at is null;

  return jsonb_build_object(
    'content_sha256', v_hash,
    'canonical', jsonb_build_object(
      'upload_id', v_canonical.id,
      'storage_key', v_canonical.storage_key,
      'verified_at', v_canonical.verified_at
    ),
    'superseded', v_superseded
  );
end;
$$;

revoke all on function public.resolve_exact_source_duplicate(uuid, text) from public;
revoke all on function public.resolve_exact_source_duplicate(uuid, text) from anon;
revoke all on function public.resolve_exact_source_duplicate(uuid, text) from authenticated;
grant execute on function public.resolve_exact_source_duplicate(uuid, text) to service_role;
